stop the workflow if unittest failed

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -82,5 +82,14 @@ jobs:
       - name: Run JASPDesktop Test
         run: |
             cd jasp-build
-            export QT_QPA_PLATFORM="vnc" 
+            export QT_QPA_PLATFORM=offscreen
             ./Tests/JASPTest &
+            TEST_PID=$!
+      
+            wait $TEST_PID
+            EXIT_CODE=$?
+      
+            if [ $EXIT_CODE -ne 0 ]; then
+              echo "Tests failed with exit code $EXIT_CODE"
+              exit $EXIT_CODE
+            fi
